version: '3.8'
services:

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27018:27017"
    networks:
      - mcs_network

  rabbitmq:
    build: 
      context: ./rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    ports:
      - "5672:5672"     # Puerto para AMQP
      - "15672:15672"   # Panel de administración
    networks:
      - mcs_network

  events-service:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: events-service
    ports:
      - "8082:8082"
    networks:
      - mcs_network
    depends_on:
      - mongodb
      - rabbitmq
    environment:

      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: mcs_events_database

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

networks:
  mcs_network:
    external: true    